SET S /S-1*S-4/;
*SET TIME /T0,T1,T2/;
*SET ACTIVOS /X1, X2/;
*SET POSIBILIDADES /UU, UD, DU, DD/;

VARIABLES RP2,W(S),Y(S);
POSITIVE VARIABLES W(S),Y(S);

EQUATIONS FO,R4;

FO.. RP2=E=Y('S-3')-4*W('S-3');
R4.. 1.25*55*1.06+1.12*1.14*0-Y('S-3')+ W('S-3')=E=70;



MODEL MARKOWIT /ALL/;

SOLVE MARKOWIT USING NLP MAXIMIZING RP2;