SET S /S-1*S-4/;
*SET TIME /T0,T1,T2/;
*SET ACTIVOS /X1, X2/;
*SET POSIBILIDADES /UU, UD, DU, DD/;

VARIABLES Z4,W(S),Y(S);
POSITIVE VARIABLES W(S),Y(S);

EQUATIONS FO,R4;

FO.. Z4=E=Y('S-4')-4*W('S-4');
R4.. 1.06*55*1.06+1.12*1.12*0-Y('S-4')+ W('S-4')=E=70;



MODEL MARKOWIT /ALL/;

SOLVE MARKOWIT USING NLP MAXIMIZING Z4;